version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: qiang-qiang-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: qiang_qiang
      MYSQL_USER: qiang
      MYSQL_PASSWORD: qiang123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - qiang-qiang-network

networks:
  qiang-qiang-network:
    driver: bridge
